"""clientes y bicicletas

Revision ID: 1f2259bc3de8
Revises: 02c627c65485
Create Date: 2026-07-19 01:27:21.974069
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1f2259bc3de8'
down_revision: str | None = '02c627c65485'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('tipo_documento', sa.Enum('DNI', 'RUC', 'CE', 'PASAPORTE', name='tipo_documento'), nullable=False),
    sa.Column('numero_documento', sa.String(length=15), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('direccion', sa.String(length=240), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clientes_nombre', 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_numero_documento'), 'clientes', ['numero_documento'], unique=False)
    op.create_index('uq_clientes_documento', 'clientes', ['tipo_documento', 'numero_documento'], unique=True)
    op.create_table('bicicletas',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('numero_serie', sa.String(length=60), nullable=True),
    sa.Column('tipo', sa.Enum('MTB', 'RUTA', 'URBANA', 'BMX', 'PLEGABLE', 'ELECTRICA', 'INFANTIL', 'OTRA', name='tipo_bicicleta'), nullable=False),
    sa.Column('rodado', sa.String(length=10), nullable=True),
    sa.Column('talla', sa.String(length=10), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bicicletas_cliente', 'bicicletas', ['cliente_id'], unique=False)
    op.create_index('uq_bicicletas_numero_serie', 'bicicletas', ['numero_serie'], unique=True, postgresql_where=sa.text('numero_serie IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_bicicletas_numero_serie', table_name='bicicletas', postgresql_where=sa.text('numero_serie IS NOT NULL'))
    op.drop_index('ix_bicicletas_cliente', table_name='bicicletas')
    op.drop_table('bicicletas')
    op.drop_index('uq_clientes_documento', table_name='clientes')
    op.drop_index(op.f('ix_clientes_numero_documento'), table_name='clientes')
    op.drop_index('ix_clientes_nombre', table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
