"""repuestos enlazados a inventario

Revision ID: daa635063a68
Revises: 1069dbfdae75
Create Date: 2026-07-19 03:48:29.981001
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'daa635063a68'
down_revision: str | None = '1069dbfdae75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ficha_repuestos', sa.Column('producto_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ficha_repuestos_producto_id'), 'ficha_repuestos', ['producto_id'], unique=False)
    op.create_foreign_key(None, 'ficha_repuestos', 'productos', ['producto_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ficha_repuestos', type_='foreignkey')
    op.drop_index(op.f('ix_ficha_repuestos_producto_id'), table_name='ficha_repuestos')
    op.drop_column('ficha_repuestos', 'producto_id')
    # ### end Alembic commands ###
