"""comprobantes electronicos

Revision ID: b259c83f460e
Revises: 04c3b1af2303
Create Date: 2026-07-19 05:26:28.522835
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b259c83f460e'
down_revision: str | None = '04c3b1af2303'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprobantes',
    sa.Column('tipo', sa.Enum('FACTURA', 'BOLETA', 'NOTA_CREDITO', name='tipo_comprobante'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'REGISTRADO', 'ACEPTADO', 'RECHAZADO', 'ANULADO', 'ERROR', name='estado_comprobante'), nullable=False),
    sa.Column('serie', sa.String(length=8), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=True),
    sa.Column('documento_afectado_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('cliente_tipo_documento', sa.String(length=2), nullable=False),
    sa.Column('cliente_numero_documento', sa.String(length=15), nullable=False),
    sa.Column('cliente_denominacion', sa.String(length=200), nullable=False),
    sa.Column('tipo_estado_sunat', sa.String(length=4), nullable=True),
    sa.Column('descripcion_estado_sunat', sa.String(length=60), nullable=True),
    sa.Column('hash_cpe', sa.String(length=120), nullable=True),
    sa.Column('qr', sa.Text(), nullable=True),
    sa.Column('xml_url', sa.String(length=400), nullable=True),
    sa.Column('pdf_url', sa.String(length=400), nullable=True),
    sa.Column('cdr_url', sa.String(length=400), nullable=True),
    sa.Column('payload_enviado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('respuesta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('motivo_anulacion', sa.String(length=300), nullable=True),
    sa.Column('fecha_anulacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('es_simulado', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_afectado_id'], ['comprobantes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comprobantes_estado', 'comprobantes', ['estado'], unique=False)
    op.create_index('ix_comprobantes_tipo', 'comprobantes', ['tipo'], unique=False)
    op.create_index(op.f('ix_comprobantes_venta_id'), 'comprobantes', ['venta_id'], unique=False)
    op.create_index('ux_comprobantes_serie_numero', 'comprobantes', ['serie', 'numero'], unique=True, postgresql_where=sa.text("estado <> 'ERROR'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_comprobantes_serie_numero', table_name='comprobantes', postgresql_where=sa.text("estado <> 'ERROR'"))
    op.drop_index(op.f('ix_comprobantes_venta_id'), table_name='comprobantes')
    op.drop_index('ix_comprobantes_tipo', table_name='comprobantes')
    op.drop_index('ix_comprobantes_estado', table_name='comprobantes')
    op.drop_table('comprobantes')
    # ### end Alembic commands ###
