"""inventario

Revision ID: 1069dbfdae75
Revises: ea97c46d4d2e
Create Date: 2026-07-19 03:19:23.299534
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1069dbfdae75'
down_revision: str | None = 'ea97c46d4d2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=240), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_table('productos',
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('unidad', sa.Enum('UNIDAD', 'PAR', 'JUEGO', 'METRO', 'LITRO', 'KIT', name='unidad_medida'), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('codigo_barras', sa.String(length=64), nullable=True),
    sa.Column('ubicacion', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stock_actual >= 0', name='ck_productos_stock_no_negativo'),
    sa.CheckConstraint('stock_minimo >= 0', name='ck_productos_minimo_no_negativo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria_id'), 'productos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_productos_codigo_barras'), 'productos', ['codigo_barras'], unique=False)
    op.create_index(op.f('ix_productos_marca'), 'productos', ['marca'], unique=False)
    op.create_index('ix_productos_nombre', 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=True)
    op.create_table('movimientos_kardex',
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', name='tipo_movimiento'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_anterior', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_posterior', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kardex_producto_fecha', 'movimientos_kardex', ['producto_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_movimientos_kardex_created_at'), 'movimientos_kardex', ['created_at'], unique=False)
    op.create_index(op.f('ix_movimientos_kardex_producto_id'), 'movimientos_kardex', ['producto_id'], unique=False)
    op.create_index(op.f('ix_movimientos_kardex_referencia'), 'movimientos_kardex', ['referencia'], unique=False)
    op.create_index(op.f('ix_movimientos_kardex_tipo'), 'movimientos_kardex', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_kardex_tipo'), table_name='movimientos_kardex')
    op.drop_index(op.f('ix_movimientos_kardex_referencia'), table_name='movimientos_kardex')
    op.drop_index(op.f('ix_movimientos_kardex_producto_id'), table_name='movimientos_kardex')
    op.drop_index(op.f('ix_movimientos_kardex_created_at'), table_name='movimientos_kardex')
    op.drop_index('ix_kardex_producto_fecha', table_name='movimientos_kardex')
    op.drop_table('movimientos_kardex')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index('ix_productos_nombre', table_name='productos')
    op.drop_index(op.f('ix_productos_marca'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo_barras'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
