"""codigo publico de ficha

Revision ID: ea97c46d4d2e
Revises: d1d86eaa3ddc
Create Date: 2026-07-19 02:38:09.481920
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Se importa la función del modelo para que el backfill use exactamente el
# mismo alfabeto y longitud que los códigos nuevos.
from app.models.ficha import generar_codigo_publico


revision: str = 'ea97c46d4d2e'
down_revision: str | None = 'd1d86eaa3ddc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # En tres pasos: la columna no puede nacer NOT NULL sobre una tabla que ya
    # tiene fichas, y un DEFAULT fijo violaría el índice único al repetirse.
    op.add_column('fichas', sa.Column('codigo_publico', sa.String(length=16), nullable=True))

    conexion = op.get_bind()
    ids = conexion.execute(sa.text("SELECT id FROM fichas")).scalars().all()
    for ficha_id in ids:
        conexion.execute(
            sa.text("UPDATE fichas SET codigo_publico = :c WHERE id = :i"),
            {"c": generar_codigo_publico(), "i": ficha_id},
        )

    op.alter_column('fichas', 'codigo_publico', nullable=False)
    op.create_index(op.f('ix_fichas_codigo_publico'), 'fichas', ['codigo_publico'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fichas_codigo_publico'), table_name='fichas')
    op.drop_column('fichas', 'codigo_publico')
    # ### end Alembic commands ###
