"""auditoria

Revision ID: c0ca8dcbbeb1
Revises: b259c83f460e
Create Date: 2026-07-19 06:51:14.481505
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c0ca8dcbbeb1'
down_revision: str | None = 'b259c83f460e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_email', sa.String(length=160), nullable=True),
    sa.Column('metodo', sa.String(length=8), nullable=False),
    sa.Column('ruta', sa.String(length=300), nullable=False),
    sa.Column('entidad', sa.String(length=40), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duracion_ms', sa.Integer(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_entidad', 'auditoria', ['entidad'], unique=False)
    op.create_index('ix_auditoria_fecha', 'auditoria', ['created_at'], unique=False)
    op.create_index('ix_auditoria_usuario', 'auditoria', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auditoria_usuario', table_name='auditoria')
    op.drop_index('ix_auditoria_fecha', table_name='auditoria')
    op.drop_index('ix_auditoria_entidad', table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
